export const animationStageLabels = {
  "animation.model-factory.weights-map": [
    "Model Factory",
    "Inference System",
    "Inside the GPU",
  ],
  "animation.model-factory.token-predictor": [
    "Example 1",
    "Example 2",
    "Example 3",
  ],
  "animation.model-factory.parameter-builder": [
    "Choose architecture",
    "Compare parameter groups",
    "Estimate memory",
  ],
  "animation.model-factory.pipeline-stages": [
    "Pretraining",
    "Supervised tuning",
    "Preference training",
    "Evaluation and release",
  ],
  "animation.model-factory.training-loop": [
    "Load batches",
    "Forward pass",
    "Measure loss",
    "Backpropagate",
    "Synchronize gradients",
    "Update weights",
    "Write checkpoint",
  ],
  "animation.model-factory.preference-trainer": [
    "Become the rater",
    "Record preferences",
    "Build the dataset",
    "Train the judge",
    "Test for bias",
  ],
  "animation.model-factory.adaptation-lab": [
    "Full fine-tuning",
    "Freeze the base",
    "Insert A and B",
    "Build delta W",
    "Merge or attach",
  ],
  "animation.model-factory.fine-tune-methods": [
    "Full fine-tuning",
    "LoRA",
    "QLoRA",
    "Adapters",
    "Prefix tuning",
  ],
  "animation.model-factory.artifact-packaging": [
    "Closed API",
    "Open weights",
    "Open-ish release",
    "Reproducible open",
  ],
  "animation.inference-system.request-arrival": [
    "Authenticate",
    "Route",
    "Admit",
    "Tokenize",
    "Batch",
  ],
  "animation.inference-system.compute-platform": [
    "Common inference core",
    "Add containers",
    "Add Kubernetes",
    "Add a virtual machine",
  ],
  "animation.inference-system.model-locality": [
    "Resolve version",
    "Read to node cache",
    "Stage in host memory",
    "Copy into HBM",
  ],
  "animation.inference-system.model-loading": [
    "Weights resident",
    "Allocate runtime",
    "Connect GPU ranks",
    "Initialize kernels",
    "Warm up",
    "Open admission",
  ],
  "animation.inference-system.prefill-decode": [
    "Admitted prompt",
    "Tokenize",
    "Prefill",
    "KV cache ready",
    "Predict next token",
    "Sample",
    "Stream first token",
    "Repeat decode",
    "Complete response",
  ],
  "animation.inference-system.multi-gpu": [
    "Independent replicas",
    "Tensor parallel",
    "Pipeline parallel",
    "Expert parallel",
  ],
  "animation.inside-gpu.throughput-silicon": [
    "Serial dependency",
    "Independent throughput",
    "Transformer matrix work",
  ],
  "animation.inside-gpu.zoom-anatomy": [
    "GPU package",
    "GPU die",
    "Selected SM",
    "Resident block",
    "Threads become warps",
    "Warp scheduler",
    "Execution pipeline",
    "Memory path",
  ],
  "animation.inside-gpu.kernel-launch": [
    "Kernel program",
    "Host enqueue",
    "Driver command",
    "Grid created",
    "Blocks dispatched",
    "Block admitted",
    "Warps formed",
    "Instruction issued",
    "Memory serviced",
    "Kernel completed",
  ],
  "animation.inside-gpu.divergence": [
    "Uniform execution",
    "Branch splits",
    "Masked path A",
    "Masked path B",
    "Reconverge",
  ],
  "animation.inside-gpu.warp-scheduler": [
    "Inspect resident warps",
    "Warp 0 issues a load",
    "Warp 0 waits",
    "Warp 1 issues",
    "Data returns",
    "Warp 0 resumes",
  ],
  "animation.inside-gpu.coalesced-memory": [
    "Request addresses",
    "Group sectors",
    "Check on-chip memory",
    "Fetch from HBM",
    "Return and reuse",
  ],
  "animation.inside-gpu.roofline": [
    "Measure work",
    "Measure bytes",
    "Compute intensity",
    "Locate the roof",
    "Choose an optimization",
  ],
  "animation.replay.one-prompt": [
    "Model artifact exists",
    "Weights load into HBM",
    "Worker becomes ready",
    "Prompt is admitted",
    "Prompt is tokenized",
    "Prefill runs on the GPU",
    "KV cache and first logits are ready",
    "First token is sampled",
    "First token is streamed",
    "Decode repeats through the GPU",
    "The response grows",
    "The request completes",
  ],
} as const;

export type AnimationStageId = keyof typeof animationStageLabels;
