export const journeyStages = [
  { label: "Learn", level: "Model", beginner: "Examples change billions of parameter values.", expert: "A distributed optimizer applies synchronized gradients to versioned parameter tensors.", failure: "Poor data or unstable optimization prevents useful capability." },
  { label: "Package", level: "Model", beginner: "Weights, config, tokenizer, and metadata form an artifact.", expert: "A manifest binds compatible shards, tensor layouts, precision, tokenizer, and operators.", failure: "Mixed versions or corrupt shards must fail integrity checks." },
  { label: "Place", level: "System", beginner: "The artifact moves through host memory into GPU HBM.", expert: "Local caches, pinned memory, device transfer, allocation, and rank placement establish residency.", failure: "Capacity, topology, or transfer errors keep readiness closed." },
  { label: "Admit", level: "System", beginner: "Routing, capacity, and batching decide when work begins.", expert: "Admission balances queue delay, workload shape, priority, and cache locality.", failure: "Over-admission turns capacity pressure into tail latency or failure." },
  { label: "Tokenize", level: "System", beginner: "Text becomes the IDs the model consumes.", expert: "Model-specific vocabulary rules and special tokens create the exact input sequence.", failure: "A mismatched tokenizer changes IDs and invalidates behavior." },
  { label: "Prefill", level: "GPU", beginner: "Prompt positions run together and create the KV cache.", expert: "Layer kernels process prompt positions and write per-layer key/value blocks.", failure: "Long prompts consume compute and cache capacity before the first token." },
  { label: "Launch", level: "GPU", beginner: "Framework operations enqueue GPU kernels.", expert: "Streams order launches, arguments, dependencies, and asynchronous completion.", failure: "Tiny launches or synchronization can make submission overhead visible." },
  { label: "Schedule", level: "GPU", beginner: "Blocks become resident and eligible warps issue.", expert: "Resource budgets admit blocks; scoreboards and pipelines determine warp eligibility.", failure: "Dependencies, divergence, or low residency leave issue slots idle." },
  { label: "Read memory", level: "GPU", beginner: "Registers, cache, shared memory, and HBM feed operands.", expert: "Coalescing, locality, cache hits, tiling, and bandwidth determine service time.", failure: "Scattered access or low reuse turns useful work into excess traffic." },
  { label: "Decode", level: "GPU", beginner: "One next-token distribution is produced per sequence.", expert: "Decode reads fixed weights and growing KV state to emit logits for each active sequence.", failure: "KV capacity or memory bandwidth can cap concurrency." },
  { label: "Sample", level: "System", beginner: "A decoding policy selects the next token.", expert: "Temperature and top-k/top-p reshape or truncate the logit-derived distribution.", failure: "Unpinned decoding settings make quality comparisons unreliable." },
  { label: "Stream", level: "System", beginner: "The token returns while unfinished sequences loop.", expert: "Stop rules and detokenization turn IDs into incremental response events.", failure: "Backpressure or cancellation must release request and cache state." },
] as const;

export const journeyStageLabels = journeyStages.map((stage) => stage.label);
